/**
 * Inhalte der 14 Modulseiten, aus den Entwuerfen uebernommen.
 * Preis, Titel und Icon stehen in module.ts — hier steht, was die Seite erzaehlt.
 *
 * `szene` waehlt die Hero-Darstellung (siehe ModulSzene.astro).
 */

export type Modulseite = {
  id: string;
  szene: string;
  h1: string;
  sub: string;
  knoepfe: { text: string; ziel: string }[];
  merkmale: string[];
  screenshot: string | null;
  ablaufTitel: string;
  ablauf: { titel: string; text: string }[];
  vertiefungTitel: string;
  vertiefungText: string;
  punkte: string[];
  wissen: { titel: string; text: string }[];
  faelle: { kennung: string; titel: string; text: string }[];
  schluss: string;
  schlussZeile: string;
  schlussKnoepfe: { text: string; ziel: string }[];
};

export const modulseiten: Modulseite[] = [
  {
    id: 'fotobox',
    szene: 'booth',
    h1: 'Der Booth, der den Abend allein durchhält',
    sub: 'Fünf Aufnahmearten, Sofortdruck, Kiosk-Betrieb und Cockpit — die Basis, auf der jedes weitere Modul aufsetzt. Läuft auf PC, Mac und iPad, auch ohne Internet.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['5 Aufnahmearten', '8 Ausgabewege', 'Offline-fähig'],
    screenshot: '/assets/shot-booth-attract.png',
    ablaufTitel: 'So läuft eine Session',
    ablauf: [{ titel: 'Modus wählen', text: 'Foto, Streifen, Boomerang, GIF oder Video — nur die Arten, die ihr freigegeben habt.' }, { titel: 'Countdown & Aufnahme', text: 'Regieanweisung, Blitz, Serie. Alles lokal, keine Wartezeit auf die Cloud.' }, { titel: 'Drucken & teilen', text: 'Sofortdruck läuft parallel, während der Gast schon den QR scannt.' }],
    vertiefungTitel: 'Kiosk, aus dem niemand herausfällt',
    vertiefungText: 'Die Oberfläche läuft im Vollbild, geschützt per PIN. Nach 45 Sekunden Leerlauf springt sie zurück in den Wartebildschirm — der nächste Gast findet immer den Startzustand.',
    punkte: ['Kamera per USB-Tethering, Hotfolder oder Webcam', 'Systemdruck: was das Betriebssystem kennt, kennt die Box', 'Fernsteuerung am Handy für Auslösen, Pause und Moderation', 'Selbstprüfung meldet Papier, Tinte und Speicher, bevor es klemmt'],
    wissen: [{ titel: '82 Vorlagen inklusive', text: 'Fotoformat und Streifen, jederzeit im Designer umbaubar.' }, { titel: 'Läuft offline', text: 'QR-Download über den eigenen Hotspot, Upload später.' }, { titel: 'Je Box lizenziert', text: 'Zusatzmodule gelten danach kontoweit für alle Boxen.' }, { titel: 'Ohne Vertrag', text: 'Monatlich kündbar, Saisonpause möglich.' }],
    faelle: [{ kennung: 'Hochzeit · 140 Gäste', titel: '137 Sessions, 212 Drucke', text: 'Ohne WLAN im Saal, Uploads liefen am Folgetag nach.' }, { kennung: 'Feste Installation', titel: '99,4 % Laufzeit', text: 'Leerlauf-Modus, Kiosk-PIN, Bezahlung vor dem Druck.' }],
    schluss: 'Fangt mit der Basis an',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: '360-booth',
    szene: 'rundum',
    h1: 'Der Rundum-Clip, der jeden Feed füllt',
    sub: 'Arm und Plattform, gesteuert aus derselben Software: Geschwindigkeit, Richtung, Vorlauf und Overlays. Der Clip ist fertig, bevor der Gast von der Plattform steigt.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Arm & Plattform', 'Tempo steuerbar', 'Overlay-Sets'],
    screenshot: null,
    ablaufTitel: 'Ein Umlauf, ein Clip',
    ablauf: [{ titel: 'Plattform betreten', text: 'Ein bis vier Personen, Haltegriff optional.' }, { titel: 'Arm läuft', text: 'Tempo, Richtung und Anzahl der Umläufe pro Event gesetzt.' }, { titel: 'Clip ausgeben', text: 'Zeitlupe, Overlay, Musikbett — direkt per QR oder Mail.' }],
    vertiefungTitel: 'Hardware, die die Software kennt',
    vertiefungText: 'youbooth steuert Motor, Licht und Kamera in einem Ablauf: Vorlauf, Aufnahme, Rücklauf. Wenn die Plattform hakt, meldet die Selbstprüfung das, bevor der nächste Gast draufsteigt.',
    punkte: ['Vorlagen für Übergänge, Logo und Musikbett inklusive', 'Auch als reiner Videomodus ohne Rotation nutzbar', 'Clips laufen in Galerie, Foto-Wall und Slideshow', 'Aufbau in 20 Minuten, Transport im Case'],
    wissen: [{ titel: 'Platz', text: 'Zwei mal zwei Meter plus Anlauf reichen.' }, { titel: 'Personen', text: 'Bis vier auf der Plattform, Gewichtsgrenze beachten.' }, { titel: 'Strom', text: 'Ein Kreis genügt für Motor, Licht und Rechner.' }, { titel: 'Wartung', text: 'Selbstprüfung testet Motorlauf vor dem Event.' }],
    faelle: [{ kennung: 'Club-Opening', titel: '340 Clips in 5 Stunden', text: 'Zwei Betreuer, kein Nachschnitt.' }, { kennung: 'Autohaus', titel: 'Fahrzeug in der Mitte', text: 'Rundum-Clip mit Produkt statt Personen.' }],
    schluss: 'Dreht auf',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'slow-motion',
    szene: 'booth',
    h1: 'Red-Carpet-Zeitlupe, direkt teilbar',
    sub: 'Kurze Clips in Zeitlupe, mit Dauerlicht und Übergängen — ohne Schnitt am Rechner. Der Clip liegt Sekunden später im QR und in der Galerie.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['120 bis 240 fps', 'Dauerlicht', 'Ohne Schnitt'],
    screenshot: null,
    ablaufTitel: 'Wie ein Clip entsteht',
    ablauf: [{ titel: 'Aufstellen', text: 'Dauerlicht statt Blitz, Kamera auf Zeitlupe konfiguriert.' }, { titel: 'Auftreten', text: 'Gäste laufen, werfen, tanzen — 6 bis 10 Sekunden reichen.' }, { titel: 'Ausgeben', text: 'Automatisch verlangsamt, mit Intro und Outro versehen.' }],
    vertiefungTitel: 'Overlays, die den Clip rahmen',
    vertiefungText: 'Animierte Rahmen, Logo-Einblendung und Übergänge kommen als Set. Ihr wählt pro Event, sonst nichts — der Clip ist fertig, wenn der Gast vor dem Screen steht.',
    punkte: ['Funktioniert mit Systemkameras und Action-Cams', 'Windmaschine und Konfettikanone lassen sich triggern', 'Clips laufen auch auf der Foto-Wall und in der Slideshow', 'Dateigröße bleibt teilbar, ohne sichtbaren Qualitätsverlust'],
    wissen: [{ titel: 'Licht ist Pflicht', text: 'Zeitlupe braucht Dauerlicht, kein Blitz.' }, { titel: 'Länge', text: '6 bis 12 Sekunden, danach wird es langweilig.' }, { titel: 'Ton', text: 'Meist ohne — in Zeitlupe klingt Ton seltsam.' }, { titel: 'Platz', text: 'Zwei Meter Anlauf reichen für den Effekt.' }],
    faelle: [{ kennung: 'Club-Event', titel: 'Schlange vor der Box', text: 'Der Clip ist geteilt, bevor der nächste Gast dran ist.' }, { kennung: 'Sponsoring', titel: 'Logo im Rahmen', text: 'Marke läuft in jedem Clip mit, ohne Aufkleber.' }],
    schluss: 'Macht Bewegung zum Bild',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'web-kamera',
    szene: 'browser',
    h1: 'Fotobox im Browser, ohne Hardware',
    sub: 'Ein Link, eine Kamera-Erlaubnis — fertig. Gut für Testphasen, verteilte Standorte und Aktionen, bei denen keine Box stehen kann.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Kein Aufbau', 'Link statt Box', 'Gleiche Vorlagen'],
    screenshot: null,
    ablaufTitel: 'Von Link zu Bild',
    ablauf: [{ titel: 'Link teilen', text: 'Pro Event eine Adresse, optional mit Passwort und Logo.' }, { titel: 'Aufnehmen', text: 'Front- oder Rückkamera, Countdown und Cheese wie am Booth.' }, { titel: 'Teilen', text: 'Direkt in die Event-Galerie, mit denselben Ausgabewegen.' }],
    vertiefungTitel: 'Dieselben Vorlagen wie im Booth',
    vertiefungText: 'Layouts, Rahmen und Texte kommen aus derselben Quelle. Was am Screen im Saal gedruckt wird, sieht im Browser gleich aus — nur ohne Drucker.',
    punkte: ['Läuft auf jedem aktuellen Handy und Laptop', 'Mehrere Standorte gleichzeitig, eine Galerie', 'Ideal für die Testphase, bevor Hardware kommt', 'Optional mit Effekt-Studio und Freistellung'],
    wissen: [{ titel: 'Ohne Installation', text: 'Kein Download, keine App-Freigabe im Unternehmen.' }, { titel: 'Mit Branding', text: 'Logo, Farben und Texte wie am Booth.' }, { titel: 'Grenzen', text: 'Kein Sofortdruck, kein Blitz — dafür überall.' }, { titel: 'Datenschutz', text: 'Aufnahme geht direkt in eure Galerie, nicht zu Dritten.' }],
    faelle: [{ kennung: 'Homeoffice-Event', titel: '120 Teilnehmer', text: 'Alle fotografierten sich am Schreibtisch, eine Wall lief live.' }, { kennung: 'Filialkette', titel: '14 Standorte', text: 'Ein Link pro Filiale, Auswertung zentral im Cockpit.' }],
    schluss: 'Testet ohne Hardware',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'einwegkamera',
    szene: 'film',
    h1: 'Jedes Handy wird zur Einwegkamera',
    sub: 'Gäste scannen den QR-Code und bekommen einen Film mit begrenzter Anzahl Aufnahmen. Kein Löschen, kein Nachschauen, kein Filter — entwickelt wird erst, wenn ihr den Film freigebt.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Film selbst durchknipsen', ziel: '#demo' }],
    merkmale: ['Keine App', 'Keine Vorschau', 'Alle Bilder bei euch'],
    screenshot: null,
    ablaufTitel: '{{ laborTitel }}',
    ablauf: [],
    vertiefungTitel: 'Warum das funktioniert',
    vertiefungText: '',
    punkte: ['Filmlänge pro Gast: 12, 24 oder 36 Aufnahmen — nachladbar auf Wunsch', 'Entwicklungszeitpunkt: sofort, um Mitternacht, am Tag danach oder von Hand', 'Look: Kleinbild-Korn, Datumsstempel, Blitz-Anmutung oder ganz neutral', 'Moderation: alles automatisch freigeben oder vorher durchsehen', 'Ausgabe: in die Event-Galerie, auf die Foto-Wall, in die Mosaik-Wand oder in den Druck'],
    wissen: [],
    faelle: [{ kennung: 'Hochzeit · 140 Gäste', titel: '1.870 Aufnahmen', text: '78 Gäste haben ihren Film benutzt, im Schnitt 24 von 24 Bildern. Entwickelt am Sonntag um 10 Uhr — der Galerie-Link wurde 640-mal geöffnet.' }, { kennung: 'Firmenfeier · 3 Standorte', titel: 'Ein Film, drei Städte', text: 'Jeder Standort bekam eigene QR-Codes, alle Bilder liefen in eine gemeinsame Entwicklung — montags als Rundmail.' }],
    schluss: 'Film ausprobieren',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'audio-gaestebuch',
    szene: 'welle',
    h1: 'Grüße, die man hört',
    sub: 'Gäste sprechen ihren Gruß ins Mikrofon, youbooth legt daraus ein Video mit Standbild und Stimme an — sofort in der Galerie, am Ende als Zusammenschnitt.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Stimme + Standbild', 'Bis 60 Sekunden', 'Zusammenschnitt'],
    screenshot: null,
    ablaufTitel: 'Sprechen, hören, behalten',
    ablauf: [{ titel: 'Aufnehmen', text: 'Ein Tap startet, ein Tap beendet. Pegelanzeige zeigt, ob es ankommt.' }, { titel: 'Prüfen', text: 'Anhören, verwerfen, neu aufnehmen — so oft der Gast will.' }, { titel: 'Ausgeben', text: 'Video mit Standbild wandert in Galerie und Zusammenschnitt.' }],
    vertiefungTitel: 'Ein Zusammenschnitt zum Schluss',
    vertiefungText: 'Aus allen Grüßen entsteht am Ende eine Datei in Reihenfolge der Aufnahme — mit Titelkarte, Namen und Uhrzeit. Ideal als Geschenk am Tag danach.',
    punkte: ['Mikrofon der Box oder ein externes Handmikro', 'Rauschunterdrückung für laute Räume', 'Text-Transkript optional, für Untertitel im Video', 'Moderation, bevor etwas in der Galerie landet'],
    wissen: [{ titel: 'Kein Videodreh', text: 'Standbild plus Stimme ist unaufwendig und wirkt.' }, { titel: 'Länge', text: 'Standard 30 Sekunden, bis 60 einstellbar.' }, { titel: 'Format', text: 'MP4 mit Standbild, überall abspielbar.' }, { titel: 'Kombinierbar', text: 'Mit dem digitalen Gästebuch als Doppelgruß.' }],
    faelle: [{ kennung: 'Hochzeit', titel: '48 Grüße, 22 Minuten', text: 'Das Paar hörte alles auf der Rückfahrt.' }, { kennung: 'Abschied', titel: 'Kollegen sprechen', text: 'Ehrlicher als eine Karte, schneller als ein Video.' }],
    schluss: 'Nimmt Stimmen mit',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'gaestebuch',
    szene: 'zettel',
    h1: 'Grüße, die als Zettelwand wachsen',
    sub: 'Gäste schreiben oder malen am Screen, fügen ihr Foto dazu — und alles erscheint als Zettelwand auf dem Beamer. Am Ende gibt es ein PDF für das Paar.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Text · Bild · Zeichnung', 'Live-Zettelwand', 'PDF zum Schluss'],
    screenshot: null,
    ablaufTitel: 'Wie ein Gruß entsteht',
    ablauf: [{ titel: 'Schreiben', text: 'Bildschirmtastatur oder Finger — Text, Zeichnung, beides.' }, { titel: 'Foto dazu', text: 'Die letzte Aufnahme kann direkt an den Gruß geheftet werden.' }, { titel: 'An die Wand', text: 'Der Zettel fällt sichtbar in die Wand, moderiert oder direkt.' }],
    vertiefungTitel: 'Am Ende ein Buch, nicht ein Ordner',
    vertiefungText: 'Nach dem Event erzeugt youbooth ein PDF im Buchformat: ein Gruß pro Seite, mit Foto und Uhrzeit. Auf Wunsch als Druckdatei für einen echten Fotobuch-Dienst.',
    punkte: ['Moderation, damit nichts Unpassendes auf dem Beamer landet', 'Eigene Zettelfarben und Schrift aus dem White-Label', 'Auch als Station auf einem zweiten Tablet nutzbar', 'Grüße erscheinen zusätzlich in der Event-Galerie'],
    wissen: [{ titel: 'Zwei Wege', text: 'Am Booth nach der Aufnahme oder an einer eigenen Station.' }, { titel: 'Zeichnen', text: 'Fingerzeichnung mit zwei Stiftbreiten, Undo inklusive.' }, { titel: 'PDF', text: 'Automatisch nach dem Event, im Kundenkonto.' }, { titel: 'Kombinierbar', text: 'Mit Audio-Gästebuch zu Grüßen mit Stimme.' }],
    faelle: [{ kennung: 'Hochzeit', titel: 'Ersetzt das Papierbuch', text: 'Niemand muss mehr Zettel sammeln oder Handschrift entziffern.' }, { kennung: 'Abschied im Büro', titel: '48 Grüße in 2 Stunden', text: 'PDF ging am nächsten Tag an die Kollegin.' }],
    schluss: 'Sammelt Grüße, nicht Zettel',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'galerie',
    szene: 'raster',
    h1: 'Alle Bilder an einem Ort, sofort teilbar',
    sub: 'Die Galerie ist das Zuhause des Events: QR am Booth, Download einzeln oder als Paket, Löschfrist offen genannt. Funktioniert auch ohne Internet über den Box-Hotspot.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Galerie öffnen', ziel: '/oberflaechen/kunden-galerie' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['QR ohne Internet', 'Passwort optional', 'Löschfrist sichtbar'],
    screenshot: '/assets/shot-galerie.png',
    ablaufTitel: 'Was Gäste erleben',
    ablauf: [{ titel: 'Scannen', text: 'QR am Booth oder auf dem Streifen — kein Tippen von Adressen.' }, { titel: 'Ansehen', text: 'Filter nach Foto, Streifen, GIF, Video und Gästebuch.' }, { titel: 'Herunterladen', text: 'Einzeln oder alles als Paket, auf Wunsch mit Passwort.' }],
    vertiefungTitel: 'Auch dem Kunden gehört die Galerie',
    vertiefungText: 'Der Auftraggeber bekommt einen eigenen Link mit allen Bildern, Statistik und Löschfrist. Ihr entscheidet, ob Gäste hochladen dürfen und ob Moderation vorgeschaltet ist.',
    punkte: ['Eigene Domain möglich, Absender bei Mails inklusive', 'Gäste-Upload für Handybilder, mit Moderation', 'Statistik: Aufrufe, Downloads, beliebteste Bilder', 'Automatische Löschung nach Frist, verlängerbar pro Kunde'],
    wissen: [{ titel: 'Ohne Internet', text: 'QR läuft über den Box-Hotspot, Upload folgt später.' }, { titel: 'Kein Speicherlimit', text: 'Pro Event zählt die Löschfrist, nicht die Menge.' }, { titel: 'Passwort', text: 'Optional pro Event, für geschlossene Feiern.' }, { titel: 'Barrierearm', text: 'Große Ziele, funktioniert auf alten Handys.' }],
    faelle: [{ kennung: 'Firmenfeier', titel: 'Freigabe geregelt', text: 'Nur Bilder mit Einwilligung landen in der Galerie.' }, { kennung: 'Hochzeit', titel: '1.204 Aufrufe', text: 'Der Link ersetzt den USB-Stick nach dem Event.' }],
    schluss: 'Gibt jedem Event sein Zuhause',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'foto-wall',
    szene: 'raster',
    h1: 'Jedes Bild landet sofort an der Wand',
    sub: 'Aufnahmen erscheinen live auf Beamer oder TV — moderiert, in wachsendem Raster oder als Mosaik, das im Laufe des Abends ein Motiv ergibt.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Mosaik-Wand ansehen', ziel: '/oberflaechen/mosaik-wand' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Beamer & TV', 'Moderation vorschaltbar', 'Hashtag-Feed'],
    screenshot: '/assets/shot-mosaik.png',
    ablaufTitel: 'Von der Box an die Wand',
    ablauf: [{ titel: 'Aufnahme entsteht', text: 'Jede Session schickt das fertige Layout direkt an die Wand-Ansicht.' }, { titel: 'Moderation', text: 'Optional: erst freigeben, dann zeigen. Gemeldete Bilder verschwinden sofort.' }, { titel: 'Wand wächst', text: 'Raster, Mosaik oder Slideshow — Kachelgröße und Tempo stellt ihr ein.' }],
    vertiefungTitel: 'Mosaik, das ein Motiv ergibt',
    vertiefungText: 'Im Mosaik-Modus setzen sich alle Aufnahmen zu einem großen Bild zusammen — Herz, Zahl oder Logo. Die neueste Aufnahme wird kurz groß gezeigt, damit Gäste sich wiederfinden.',
    punkte: ['Läuft parallel zum Booth, ohne zweiten Rechner', 'Hashtag-Einspeisung mit Moderation aus dem Cockpit', 'Gäste-Uploads erscheinen in derselben Wand', 'Vollbild ohne Bedienelemente — nichts, was Gäste antippen könnten'],
    wissen: [{ titel: 'Zwei Ausgaben', text: 'Beamer und TV gleichzeitig, unterschiedliche Layouts möglich.' }, { titel: 'Reihenfolge', text: 'Neueste zuerst oder Zufall, mit Wiederholungsschutz.' }, { titel: 'Ohne Netz', text: 'Lokale Wand funktioniert im Box-Hotspot.' }, { titel: 'Branding', text: 'Logo, Titel und Laufband aus dem White-Label.' }],
    faelle: [{ kennung: 'Hochzeit', titel: 'Wand als Gesprächsstoff', text: 'Gäste warten auf ihr Bild und schauen sich die anderen an.' }, { kennung: 'Messe', titel: 'Aufmerksamkeit am Gang', text: 'Große Wand zieht Besucher an den Stand, ohne Personal.' }],
    schluss: 'Bringt die Bilder an die Wand',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'slideshow',
    szene: 'buehne',
    h1: 'Vollbild-Diashow für Pausen und Empfang',
    sub: 'Ruhige Bildfolge auf Beamer oder TV: eigene Zwischenbilder, sanfte Bewegung, Tempo einstellbar. Ohne Bedienelemente, damit niemand hineingreift.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Vollbild', 'Ken-Burns-Bewegung', 'Eigene Zwischenbilder'],
    screenshot: null,
    ablaufTitel: 'Aufsetzen und laufen lassen',
    ablauf: [{ titel: 'Quelle wählen', text: 'Live vom Booth, aus der Galerie oder ein eigener Ordner.' }, { titel: 'Rhythmus setzen', text: 'Anzeigedauer, Übergang, Bewegung, Zwischenbilder.' }, { titel: 'Vollbild starten', text: 'Läuft dauerhaft, startet nach Stromausfall selbst neu.' }],
    vertiefungTitel: 'Zwischenbilder für Programmpunkte',
    vertiefungText: 'Zwischen den Fotos laufen eigene Tafeln: Menü, Danksagung, nächster Programmpunkt. So wird aus der Diashow ein Infokanal, der niemanden störend anspricht.',
    punkte: ['Mehrere Ausgaben mit unterschiedlichem Inhalt', 'Hoch- und Querformat, auch Portrait-Screens', 'Musikhinweis: Ton bleibt bei euch, wir zeigen nur Bild', 'Läuft im Box-Hotspot, ganz ohne Internet'],
    wissen: [{ titel: 'Sanft', text: 'Ken-Burns-Bewegung statt harter Schnitte.' }, { titel: 'Moderiert', text: 'Nur freigegebene Bilder, wenn ihr das wollt.' }, { titel: 'Robust', text: 'Autostart, Bildschirmschoner aus, Wiederaufnahme.' }, { titel: 'Kombinierbar', text: 'Mit Foto-Wall im Wechsel auf demselben Beamer.' }],
    faelle: [{ kennung: 'Empfang', titel: 'Warten wird kurzweilig', text: 'Gäste sehen Bilder vom Sektempfang, während gedeckt wird.' }, { kennung: 'Messe', titel: 'Endlosschleife', text: 'Standbetreuung braucht sich nicht um die Anzeige zu kümmern.' }],
    schluss: 'Füllt die große Fläche',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'effekt-studio',
    szene: 'kacheln',
    h1: 'Kunststile und Hintergründe, ohne Greenscreen',
    sub: 'Freistellung per KI, austauschbare Hintergründe und sechs Bildstile — pro Event auswählbar, mit Vorschau am Screen, bevor der Gast entscheidet.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Freistellung ohne Tuch', '6 Stile', 'Eigene Hintergründe'],
    screenshot: null,
    ablaufTitel: 'Vom Rohbild zum Look',
    ablauf: [{ titel: 'Freistellen', text: 'KI erkennt Personen, ganz ohne Greenscreen-Tuch.' }, { titel: 'Hintergrund', text: 'Aus 24 Motiven oder eigenen Bildern, pro Event freigegeben.' }, { titel: 'Stil auflegen', text: 'Aquarell, Comic, Kohle, Retro-Film, S/W, Neon — Stärke einstellbar.' }],
    vertiefungTitel: 'Der Gast sieht, was er bekommt',
    vertiefungText: 'Alle Effekte laufen in der Live-Vorschau, nicht erst nach dem Auslösen. Aktive Effekte stehen als Chips über dem Bild, damit niemand rätselt, warum er anders aussieht.',
    punkte: ['Klassischer Greenscreen bleibt möglich, wenn ein Tuch steht', 'Kantenweichheit einstellbar, für schwierige Haare', 'Gast darf den Hintergrund selbst wählen — oder eben nicht', 'Stile gelten für Foto, Streifen, GIF und Boomerang'],
    wissen: [{ titel: 'Läuft lokal', text: 'Freistellung passiert auf dem Box-Rechner, nicht in der Cloud.' }, { titel: 'Tempo', text: 'Kein spürbarer Aufschlag auf die Session-Dauer.' }, { titel: 'Eigene Motive', text: 'Hintergründe als Paket einspielbar, pro Event zuweisbar.' }, { titel: 'Grenzen', text: 'Sehr dunkle Räume brauchen Dauerlicht für saubere Kanten.' }],
    faelle: [{ kennung: 'Messe', titel: 'Standdesign im Bild', text: 'Hintergrund zeigt das Produkt, ohne Aufbau eines Sets.' }, { kennung: 'Kindergeburtstag', titel: 'Dschungel und Weltraum', text: 'Kinder wählen selbst — der Renner des Nachmittags.' }],
    schluss: 'Gibt jedem Bild einen Look',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'foto-finder',
    szene: 'suche',
    h1: 'Ein Selfie, und der Gast hat seine Bilder',
    sub: 'Statt 400 Fotos zu durchscrollen: Gesicht scannen, Treffer bekommen. Das Suchbild bleibt auf dem Gerät und wird nach der Suche verworfen.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Am Handy', 'Einwilligung vorab', 'Suchbild wird verworfen'],
    screenshot: null,
    ablaufTitel: 'Drei Schritte für den Gast',
    ablauf: [{ titel: 'Einwilligung', text: 'Ein Screen erklärt in drei Sätzen, was passiert — und was nicht.' }, { titel: 'Selfie', text: 'Frontkamera, Gesicht in den Rahmen. Läuft im Browser, ohne App.' }, { titel: 'Treffer', text: 'Eigene Bilder, sortiert nach Ähnlichkeit, als Paket herunterladbar.' }],
    vertiefungTitel: 'Datenschutz, der auf dem Screen steht',
    vertiefungText: 'Keine Gesichtsprofile, keine Weitergabe: Das Selfie dient als Suchschlüssel und wird nach dem Treffer verworfen. Wer nicht will, nutzt die vollständige Galerie weiter.',
    punkte: ['Findet auch Gruppenbilder, in denen der Gast nur am Rand steht', 'Fehltreffer meldet der Gast mit einem Tap', 'Läuft in der Event-Galerie, kein zweites Portal', 'Abschaltbar pro Event, wenn der Kunde es nicht möchte'],
    wissen: [{ titel: 'Im Browser', text: 'Kein App-Zwang, funktioniert auf iOS und Android.' }, { titel: 'Sekunden statt Minuten', text: 'Suche über 400 Bilder dauert wenige Sekunden.' }, { titel: 'Sortiert', text: 'Sicherster Treffer zuerst, danach absteigend.' }, { titel: 'Löschfrist', text: 'Endet mit der Galerie, standardmäßig nach 30 Tagen.' }],
    faelle: [{ kennung: 'Hochzeit', titel: 'Am Tag danach', text: 'Gäste finden ihre Bilder ohne Nachfragen beim Paar.' }, { kennung: 'Großveranstaltung', titel: '5.000 Fotos', text: 'Ohne Suche unbenutzbar — mit Suche ein Selbstläufer.' }],
    schluss: 'Macht Suchen zum Selbstläufer',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'event-seiten',
    szene: 'browser',
    h1: 'Eine kleine Website pro Event',
    sub: 'Ablauf, Galerie-Link, Hashtag, Upload und Kontakt — gebrandet in eurer oder der Kundenmarke, in fünf Minuten aufgesetzt.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Eigene Adresse', 'Ablauf & Galerie', 'Upload für Gäste'],
    screenshot: null,
    ablaufTitel: 'In fünf Minuten online',
    ablauf: [{ titel: 'Vorlage wählen', text: 'Drei Grundlayouts, jeweils in eurer oder Kundenmarke.' }, { titel: 'Inhalte einsetzen', text: 'Ablauf, Text, Bilder, Galerie-Link und Hashtag.' }, { titel: 'Veröffentlichen', text: 'Eigene Adresse oder Subdomain, QR gleich mitgeliefert.' }],
    vertiefungTitel: 'Der Link, den Gäste behalten',
    vertiefungText: 'Die Event-Seite überlebt den Abend: dort liegen Galerie, Gästebuch-PDF und Kontakt. Für Vermieter ein sauberer Abschluss — und ein sichtbarer Verweis auf euch.',
    punkte: ['Pro Event eine Seite, ohne Website-Baukasten', 'Passwortschutz für geschlossene Feiern', 'Upload-Bereich speist Galerie und Foto-Wall', 'SEO-arm gehalten: die Seite ist für Gäste, nicht für Google'],
    wissen: [{ titel: 'Marke', text: 'Vollständig White-Label, auch im Mail-Absender.' }, { titel: 'QR', text: 'Automatisch erzeugt, für Karten und Aufsteller.' }, { titel: 'Mobil zuerst', text: 'Fast alle Gäste kommen per Handy.' }, { titel: 'Archiv', text: 'Seite bleibt bis zur Löschfrist erreichbar.' }],
    faelle: [{ kennung: 'Hochzeit', titel: 'Ablauf statt Nachfragen', text: 'Gäste sehen, wann was passiert — und wo die Bilder liegen.' }, { kennung: 'Firmenfeier', titel: 'Interne Freigabe', text: 'Passwort und Löschfrist auf die Compliance abgestimmt.' }],
    schluss: 'Gibt jedem Event eine Adresse',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
  {
    id: 'vermietung',
    szene: 'kalender',
    h1: 'Buchungsseite, Kalender, Verträge — ein Konto',
    sub: 'Öffentliche Buchungsseite mit echter Verfügbarkeit, daraus Angebot, Vertrag und Anzahlung. Aus der bestätigten Anfrage entsteht automatisch das Event für die Box.',
    knoepfe: [{ text: 'Kostenlos testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
    merkmale: ['Keine Doppelbuchung', 'Vertrag & Anzahlung', 'Event entsteht automatisch'],
    screenshot: '/assets/shot-cockpit.png',
    ablaufTitel: 'Von der Anfrage zum Event',
    ablauf: [{ titel: 'Kunde fragt an', text: 'Datum prüfen, Paket wählen, Konto anlegen — alles auf einer Seite.' }, { titel: 'Ihr bestätigt', text: 'Verfügbarkeit der Boxen ist bekannt, Angebot geht mit einem Klick raus.' }, { titel: 'Box lädt das Event', text: 'Branding, Vorlagen und Module sind dem Termin schon zugeordnet.' }],
    vertiefungTitel: 'Was danach von allein läuft',
    vertiefungText: 'Vertrag und Anzahlung, Erinnerung sieben Tage vorher, Packliste je Paket, Galerie-Link nach dem Event. Ihr greift nur ein, wenn jemand etwas Besonderes will.',
    punkte: ['Blockzeiten für Wartung, Urlaub und Transport', 'Pakete, Zusatzstunden und Kaution pflegt ihr einmal', 'Zahlungsstand steht am Auftrag, ohne Extra-Tool', 'Statistik pro Event als Beleg für die Schlussrechnung'],
    wissen: [{ titel: 'Eigene Marke', text: 'Buchungsseite mit eurer Domain, ohne youbooth-Logo.' }, { titel: 'Mehrere Boxen', text: 'Kalender kennt jede Box einzeln.' }, { titel: 'Anfragen', text: 'Rückfragen laufen im Auftrag, nicht im Mail-Chaos.' }, { titel: 'Export', text: 'Buchungen als CSV für die Buchhaltung.' }],
    faelle: [{ kennung: 'Vermieter mit 3 Boxen', titel: '62 % Auslastung im August', text: 'Kalender verhinderte jede Doppelbuchung.' }, { kennung: 'Nebengewerbe', titel: 'Erste Buchungsseite in 2 Tagen', text: 'Ohne Website-Baukasten, direkt aus dem Cockpit.' }],
    schluss: 'Macht aus Anfragen Termine',
    schlussZeile: '14 Tage vollständig testen, ohne Kreditkarte.',
    schlussKnoepfe: [{ text: 'Modul testen', ziel: '/kontakt' }, { text: 'Alle Module', ziel: '/module' }],
  },
];
